### ISSUE TITLE
Upload photo on 'manage department' cannot change 

### ISSUE THREAD

**Issue by Macairing** [itsmarawi/ranao-hrs-quasar#393]
step to reproduce :

- [ ] logged in as HR Admin /Personnel 
- [ ] click **office module**
- [ ] select **manage department**
- [ ] click **upload photo**
-
expected output:

- it should change the **profile logo**

 actual output:

- it cannot change the profile logo instead it directly change the profile photo of the employee

![22](https://user-images.githubusercontent.com/105042047/167091144-c211d1a3-e5fa-4061-979c-4b852f81a939.JPG)

**Comment by maryamdanieza** [comment]
Fixed Issue 👍
