### ISSUE TITLE
Salary of the Employee doesn't match

### ISSUE THREAD

**Issue by maryamdanieza** [itsmarawi/ranao-hrs-quasar#395]
Steps to reproduce;

- [ ] logged in as an HR Admin/Personnel/Employee
- [ ] Click '**My request**' on Profile icon
- [ ] Select '**Approved'** tab
- [ ] Select any request
- [ ] **Download/Print** the request
- [ ] Compare the **Salary of Printed/Downloaded COE** to **Actual salary** of the Employee

Expected output;

- Should match the **salary of Downloaded/Printed COE** to **Actual salary** of the Employee

Actual output;
- **Doesn't match the Actual Salary to Downloaded/Printed COE**

![salary](https://user-images.githubusercontent.com/80914662/167233999-4285d40d-d00e-404f-9625-e16607f6efbe.PNG)
![salary1](https://user-images.githubusercontent.com/80914662/167234007-453d1b7b-62da-4d0e-a9e6-0f5ce5db2dc4.PNG)

**Comment by apsolaiman** [comment]
This is not an issue. Annual Salary is calculated in COE.
