### ISSUE TITLE
[Filter Pop-up dialog] close button not working

### ISSUE THREAD

**Issue by amersarosong** [itsmarawi/ranao-hrs-quasar#402]
Steps to reproduce

- [ ] log in as admin
- [ ] got to employees page
- [ ] click on the filter button beside search input field
- [ ] a pop dialog will show
- [ ] click the close button

Expected output:

- [ ] Dialog will be closed

Actual output:

- [ ] not able to close the dialog

**Comment by usman0512** [comment]
This is already fixed

**Comment by usman0512** [comment]
This is already fixed
