### ISSUE TITLE
[Mobile View] [Advanced Search] - UI

### ISSUE THREAD

**Issue by Jawharah2000** [itsmarawi/ranao-hrs-quasar#415]
steps to reproduce:

- [ ]  Logged in as an HR admin/HR Personnel/ICTO using mobile
- [ ] Go to Employee module and Account module
- [ ] Click the Search filter button

expected output
The dialog box should be fit to the mobile screen

actual output
when you click search filter button, the dialog unfit to the mobile screen.

![advance search](https://user-images.githubusercontent.com/80914662/168550113-08f98570-615d-428a-a98d-46cdd7c40d90.PNG)
![account bugs jpg1](https://user-images.githubusercontent.com/89053260/168708922-4a416903-db13-47ab-a95a-c0f5837b31e3.jpg)

by: jaw and inshidar

**Comment by maryamdanieza** [comment]
Fixed Issue.
