### ISSUE TITLE
[Dashboard-Clickable Charts Filter] Incorrect Data Output when Semester and Department is Filtered

### ISSUE THREAD

**Issue by Macairing** [itsmarawi/ranao-hrs-quasar#439]
Step to reproduce:
- [ ] Logged in as a **HR Admin/HR Personnel**
- [ ] Access the **Dashboard** page.
- [ ] Select the **2nd Semester or Annually** in the 'Semester Selection Box' then select the other categories in the 'Department Selection Box'

Expected output:
- It should filter the data displayed in the dashboard by the selected semester and department.

Actual output:

- When you click some of the legends, it displays ALL of the data.

![1212](https://user-images.githubusercontent.com/105042047/168955854-93f50e6a-bd68-4dc6-a362-19cc8e55aab8.JPG)
![12312](https://user-images.githubusercontent.com/105042047/168955979-57da202c-f07f-43c9-a842-b3306dc7438d.JPG)

By; Jal and Reshyl

**Comment by apsolaiman** [comment]
Closing this as it was included as tickets in Sprint 2
