### ISSUE TITLE
[Administrator] Request Module

### ISSUE THREAD

**Issue by Macairing** [itsmarawi/ranao-hrs-quasar#447]
Step to reproduce:
- [ ]  Logged in as **Administrator**
- [ ] Access the **Requests Module**

 Expected output:
-  **Administrator** must not view the 'REQUEST' if he/she are not directly addresses or not included on the **Assignee**

Actual output:
When the Administrator go to **'request module'** he/ she can view all of the request that should be not addresses to him/her.
![Admin](https://user-images.githubusercontent.com/105042047/169195428-8a825c01-8560-4c2f-9cc3-c8a16abf25fa.JPG)

**By; Jal and Norol**

**Comment by jhnsunny** [comment]
Kindly also Check this **Repetitive** notification of User Activation at the _Pending Tab_ and _Approved Tab_.
![reqmod](https://user-images.githubusercontent.com/93305452/170418623-6d3c47e9-e224-4c19-8172-867859524347.png)

**Comment by maryamdanieza** [comment]
issue fix 🤙
