### ISSUE TITLE
[Employee Module] "Close" button at employee profile

### ISSUE THREAD

**Issue by JawharahS** [itsmarawi/ranao-hrs-quasar#455]
**[DESKTOP VIEW]**
Steps to reproduce:

- [ ] Log in as Admin/HR Admin/HR Personnel
- [ ] Go to Employees page
- [ ] Select an employee at the employee list, a **SIDE PANEL employee** profile appears
- [ ] Click the "Close" button

Actual: Cannot be able to click the close button. 

Expected: The close button should be _working/**responsive**_ and be able to close the sidepanel profile of employee despite  whatever your desktop resolution is.
![sidepa](https://user-images.githubusercontent.com/93305452/174422190-917e7992-30cf-46df-a554-6b96d9bca696.png)

**Comment by jhnsunny** [comment]
Steps to reproduce:

- [ ] Log in as Admin/HR Admin/HR Personnel
- [ ] Go to Employees page
- [ ] Select an employee at the employee list, a **SIDE PANEL employee** profile appears
- [ ] Click the "Close" button

Actual: Cannot be able to click the close button. (On another note: Try minimizing your desktop resolution, the button will work.)

Expected: The close button should be _working/**responsive**_ and be able to close the sidepanel profile of employee despite of whatever your desktop resolution is.
