### ISSUE TITLE
[Administrator Account][My Request]

### ISSUE THREAD

**Issue by JawharahS** [itsmarawi/ranao-hrs-quasar#463]
steps to reproduce:

- [ ] Logged in as an ICTO
- [ ] Go to Avatar profile icon
- [ ] Click **My Request**
- [ ] Click **Request** button
- [ ] Fill out the filled required
- [ ] Click Request button

Expected output:

- After you request, the **Requested Form** should display in the **pending / approved / rejected**

Actual output:

- The requested form doesn't display in the pending / approved / rejected

![coe](https://user-images.githubusercontent.com/89053260/169460292-c21ae5cf-1557-47cc-9d62-806f2fc77b78.jpg)
![coe1](https://user-images.githubusercontent.com/89053260/169460322-ee61d025-7382-4715-893c-b3c36694f7f9.jpg)
![coe2](https://user-images.githubusercontent.com/89053260/169460338-cbc0b3e2-c731-495c-b740-8e4ddeb81000.jpg)
![coe3](https://user-images.githubusercontent.com/89053260/169460347-f7e0a71e-944f-4d3d-b356-1d83ccc770ab.jpg)

by:  jaw and inshidar

**Comment by maryamdanieza** [comment]
issue fixed 🤙
