### ISSUE TITLE
[Administrator][Activate Account]

### ISSUE THREAD

**Issue by Macairing** [itsmarawi/ranao-hrs-quasar#485]
Step to reproduce:
- [x] Logged in as Administrator
- [x] Go to Employees Module and Add an Employee
- [x] Logout admin account and sign up the added employee, you will be successfully notified for the activation of account 
- [x] Login the admin account again for user activation
- [x]  Click the **'Account'** submodule under the 'Administrative' module

Expected Output:
- You can **Activate the Pending account** and can **search it in accounts page.**

Actual Output:
- Cannot activate the pending account because it wont appear on the list of accounts. But can search on 'Employees' page.

![insidar](https://user-images.githubusercontent.com/105042047/169759846-ed311763-8b03-467d-ae33-9e7f06640c31.jpg)
![norol](https://user-images.githubusercontent.com/105042047/169759880-d2253010-692b-4c2b-bba4-5d41bf2d2e71.jpg)

Inshidar and Norol

**Comment by ruzlicali16** [comment]
Salam. I tried it in both local env and prod env and it is working. I think hindi nakapasok talaga young gi add nyo na employee. Try nyo ulit mag add with unique information and register nyo ulit hoping gagana na yan. Close nyo lang tong issue if working na cya. Thanks!
