### ISSUE TITLE
The updated info of the Employee must be persistent

### ISSUE THREAD

**Issue by Macairing** [itsmarawi/ranao-hrs-quasar#598]
**_This is a rare case scenario_**
Example: Your original Name is **Inshidar P. Panganting** tapos you updated your Name to **Hajja Inshidar P. Panganting** now, if you request a COE then yung madidisplay sa **_Request Module_** is your old name which is yung **Inshidar** instead of **Hajja Inshidar**

Step to Reproduce:
- [ ] Logged in as a ICTO/HR Admin/HR Personnel/Employee
- [ ] Go to Employees module 
- [ ] Select one of the Employee list to update his / her profile
- [ ] _After updating_, Go to **"My Request Module"** under profile icon
- [ ] Click **'Request'** 
- [ ] Fill up all the required fields
- [ ] Select request

Expected Output:
- Should display the updated Name of the employee instead of the old one.

![Old_Name](https://user-images.githubusercontent.com/105042047/174003971-1a236872-bdf0-4606-8f36-fb6612ec6a47.png)
![Updated Name](https://user-images.githubusercontent.com/105042047/174004009-403f30e0-b9a2-4dc8-ae90-819e0db201d0.png)
![Old name](https://user-images.githubusercontent.com/105042047/174004106-8571738f-4687-4a39-b3a7-09a4a0b152fa.png)

**Comment by maryamdanieza** [comment]
Fixed Issue. 👍
